# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: flutter pub get

      - name: build ipa
        run: flutter build ios --debug --no-codesign
      
      - name: mkdir payload and copy .app to Payload/
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
      - name: Compress to zip(ipa)
        run: zip -r app-debug.ipa Payload
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios
          path: app-debug.ipa
          
  build_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: flutter pub get

      - name: build apk
        run: flutter build apk --debug 
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-debug.apk
          
  build_macos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: flutter pub get

      - name: build .app
        run: flutter build macos --debug 
      
      - name: Compress to zip
        run: |
          cp -r build/macos/Build/Products/Debug/FileTrucker.app FileTrucker.app
          zip -r app-debug.zip FileTrucker.app
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: app-debug.zip
          
