name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: build ipa (iOS cant run debug app without pc, make release app.)
        run: flutter build ios --release --no-codesign
      
      - name: mkdir payload and copy .app to Payload/
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
      - name: Compress to zip(ipa)
        run: zip -r app-release.ipa Payload
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios
          path: app-release.ipa
          
  build_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: build apk
        run: flutter build apk --debug 
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-debug.apk
          
  build_macos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter config --enable-macos-desktop
          flutter pub get

      - name: build app
        run: flutter build macos --debug 
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: build/macos/Build/Products/Debug/FileTrucker.app
  
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'

      - name: Install dependencies
        run: | 
          flutter config --enable-windows-desktop
          flutter pub get

      - name: build
        run: flutter build windows --debug 

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-x64
          path: build\windows\runner\Debug

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev
          flutter config --enable-linux-desktop
          flutter pub get

      - name: build bundle
        run: flutter build linux --debug 

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-x64
          path: build/linux/x64/debug/bundle
