name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-15

    steps:
      - name: Set xcode version
        run: sudo xcode-select -s "/Applications/Xcode_16.app"

      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          cache-key: flutter_mac
          cache-path: ${{ runner.tool_cache }}/flutter_mac
          pub-cache-key: flutter_mac_pubcache
          pub-cache-path: ${{ runner.tool_cache }}/flutter_mac_pubcache

      - name: Install dependencies
        run: flutter pub get

      - name: build ipa
        run: flutter build ios -v --flavor prod --release --no-codesign
      
      - name: mkdir payload and copy .app to Payload/
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/FileTrucker.app Payload/
      - name: Compress to zip(ipa)
        run: zip -r app-release.ipa Payload
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: app-release.ipa
          
  build_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          cache-key: flutter_linux
          cache-path: ${{ runner.tool_cache }}/flutter_linux
          pub-cache-key: flutter_linux_pubcache
          pub-cache-path: ${{ runner.tool_cache }}/flutter_linux_pubcache

      - name: Install dependencies
        run: flutter pub get

      - name: build apk
        run: flutter build apk -v --flavor prod --release
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-prod-release.apk
          
  build_macos:
    runs-on: macos-15
    
    steps:
      - name: Set xcode version
        run: sudo xcode-select -s "/Applications/Xcode_16.app"

      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          cache-key: flutter_mac
          cache-path: ${{ runner.tool_cache }}/flutter_mac
          pub-cache-key: flutter_mac_pubcache
          pub-cache-path: ${{ runner.tool_cache }}/flutter_mac_pubcache

      - name: Install dependencies
        run: |
          flutter config --enable-macos-desktop
          flutter pub get

      - name: build app
        run: |
          flutter build macos -v --flavor prod --release
          mkdir output
          cd build/macos/Build/Products/Release-prod/
          cp -r FileTrucker.app ../../../../../output/
          cd ../../../../../
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal
          path: output
  
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          cache-key: flutter_win
          cache-path: ${{ runner.tool_cache }}/flutter_win
          pub-cache-key: flutter_win_pubcache
          pub-cache-path: ${{ runner.tool_cache }}/flutter_win_pubcache

      - uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install minisign -y
          
      - uses: ilammy/setup-nasm@v1

      - name: Install dependencies
        run: | 
          flutter config --enable-windows-desktop
          flutter pub get

      - name: build
        run: flutter build windows -v --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: build\windows\x64\runner\Release

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          cache-key: flutter_linux
          cache-path: ${{ runner.tool_cache }}/flutter_linux
          pub-cache-key: flutter_linux_pubcache
          pub-cache-path: ${{ runner.tool_cache }}/flutter_linux_pubcache

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev libsodium-dev
          flutter config --enable-linux-desktop
          flutter pub get

      - name: build bundle
        run: flutter build linux -v --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: build/linux/x64/release/bundle
