name: Remove old artifacts

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '7 days'
